theme: just-the-docs
url: https://just-the-docs.github.io
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  

# theme: jekyll-theme-minimal
title: w4os - WordPress Interface for OpenSimulator
# description: [A short description of your site's purpose]
#logo: [Location of the logo]
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
